# Generated by Django 3.2 on 2021-04-08 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('symbol', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_stock', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numstocks', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stocksymbol')),
            ],
        ),
        migrations.CreateModel(
            name='Stockprice',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adjusted_close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.IntegerField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stocksymbol')),
            ],
        ),
    ]
