# Generated by Django 3.2 on 2021-04-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
